# Exploring the Raspberry Pi 2 with C++ (ISBN 978-1-4842-1738-2)
# by Warren Gay VE3WWG
# LGPL2 V2.1

clobber:
	rm -fr ./modules ./lib ./.tmp_versions
	rm -f *.ko *.o *.mod.c *.symvers modules.order
	rm -f .[a-z]* .*.tmp

